on:
  workflow_dispatch: {}
  schedule:
  - cron: 0 */3 * * *

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.removeLabel({
              issue_number: 1,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'bug'
            })
            github.issues.addLabels({
              issue_number: 1,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['bug']
            })
